services:
  # Serviço do PHP para a segunda API
  second-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multi-habilit-back
    volumes:
      - ./:/var/www
    networks:
      - formulario-cadastro  # Conectando à rede do banco de dados existente
    depends_on:
      - db  # Dependendo do banco de dados existente
    command: >
      sh -c "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
         chmod -R 775 /var/www/storage /var/www/bootstrap/cache &&
         php artisan serve --host=0.0.0.0 --port=8081"
    ports:
      - "8081:8081"  # Porta diferente para a segunda API

networks:
  formulario-cadastro:
    external: true  # Rede compartilhada com a primeira API e banco de dados
