services:
  # Backend da API
  multi-habilit-back-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multi-habilit-back
    volumes:
      - ./:/var/www
      - /var/www/vendor
    depends_on:
      - multi-habilit-back-db
      - db
    command: >
      sh -c "php artisan serve --host=0.0.0.0 --port=8081"
    ports:
      - "8081:8081"

  # Banco de Dados do Backend
  multi-habilit-back-db:
    image: mysql:8.0
    container_name: mysql_db_multi_habilit_back
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: multi-habilit-back
      MYSQL_PASSWORD: root
    volumes:
      - multi_habilit_back_dbdata:/var/lib/mysql
    ports:
      - "3310:3306"

  # Banco de Dados para Outro Uso
  # db:
  #   image: mysql:8.0
  #   container_name: mysql_db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: multi-habilit
  #     MYSQL_PASSWORD: root
  #   volumes:
  #     - dbdata:/var/lib/mysql
  #   ports:
  #     - "3309:3306"

volumes:
  multi_habilit_back_dbdata:
  dbdata:
